name: mirror-to-new-repo
author: gendloop
description: '将当前仓库所有内容镜像到另一远程仓库'
inputs:
# Required
  repo:
    description: 'New repo url. e.g. https://github.com/gendloop/reponame.git'
    required: true
    default: ''
  token:
    description: 'Personal token'
    required: true
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: checkout-repo
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: push-mirror
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git pull
        git push --mirror ${{ inputs.repo }}
